language: ruby
rvm:
  - ruby-1.9.3-p484

before_script:
  - RAILS_ENV=test

bundler_args: --without='development production'

notifications:
  email: false

cache:
  - bundler

script: "bundle exec rspec --format progress"
