language: ruby
rvm:
  - ruby-1.9.3-p484

notifications:
  email: false

cache:
  - bundler

before_script:
  - mysql -e 'create database myapp_test;'
  - cp config/database_travis.yml config/database.yml
  - cp config/awesome_tasks.travis.yml config/awesome_tasks.yml
  - RAILS_ENV=test bundle exec rake db:migrate

addons:
  code_climate:
    repo_token: 3daede890e781c281bf96d996ed435a2f676b822f329198d2cb01fab9c44ebb1

script: "bundle exec rspec --format progress"
