# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{knjtasks}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kasper Johansen"]
  s.date = %q{2012-10-11}
  s.description = %q{A longer description will come...}
  s.email = %q{k@spernj.org}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "files/database_schema.rb",
    "lib/knjtasks.rb",
    "locales/da_DK/LC_MESSAGES/default.mo",
    "locales/da_DK/LC_MESSAGES/default.po",
    "locales/da_DK/title.txt",
    "locales/en_GB/title.txt",
    "models/class_comment.rb",
    "models/class_customer.rb",
    "models/class_email_check.rb",
    "models/class_project.rb",
    "models/class_task.rb",
    "models/class_task_assigned_user.rb",
    "models/class_task_check.rb",
    "models/class_timelog.rb",
    "models/class_user.rb",
    "models/class_user_project_link.rb",
    "models/class_user_rank.rb",
    "models/class_user_rank_link.rb",
    "models/class_user_task_list_link.rb",
    "pages/admin.rhtml",
    "pages/comment_edit.rhtml",
    "pages/comment_update_id_per_obj.rhtml",
    "pages/customer_edit.rhtml",
    "pages/customer_search.rhtml",
    "pages/customer_show.rhtml",
    "pages/frontpage.rhtml",
    "pages/project_edit.rhtml",
    "pages/project_search.rhtml",
    "pages/project_show.rhtml",
    "pages/task_check_edit.rhtml",
    "pages/task_edit.rhtml",
    "pages/task_search.rhtml",
    "pages/task_show.rhtml",
    "pages/timelog_edit.rhtml",
    "pages/timelog_search.rhtml",
    "pages/user_edit.rhtml",
    "pages/user_login.rhtml",
    "pages/user_profile.rhtml",
    "pages/user_rank_search.rhtml",
    "pages/user_search.rhtml",
    "pages/user_show.rhtml",
    "pages/workstatus.rhtml",
    "scripts/fckeditor_validate_login.rb",
    "spec/knjtasks_spec.rb",
    "spec/spec_helper.rb",
    "threads/thread_mail_task_comments.rb",
    "www/api/task.rhtml",
    "www/api/user.rhtml",
    "www/clean.rhtml",
    "www/css/default.css",
    "www/gfx/body_bg.jpg",
    "www/gfx/button_bg.png",
    "www/gfx/main_box_design.png",
    "www/gfx/main_box_left.png",
    "www/gfx/main_box_right.png",
    "www/gfx/main_box_top.png",
    "www/gfx/main_box_top_left.png",
    "www/gfx/main_box_top_right.png",
    "www/index.rhtml",
    "www/js/default.js"
  ]
  s.homepage = %q{http://github.com/kaspernj/knjtasks}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A task system for managing various projects, timelogs and much more.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<knjrbfw>, [">= 0"])
      s.add_runtime_dependency(%q<datet>, [">= 0"])
      s.add_runtime_dependency(%q<hayabusa>, [">= 0"])
      s.add_development_dependency(%q<http2>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.3"])
    else
      s.add_dependency(%q<knjrbfw>, [">= 0"])
      s.add_dependency(%q<datet>, [">= 0"])
      s.add_dependency(%q<hayabusa>, [">= 0"])
      s.add_dependency(%q<http2>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
    end
  else
    s.add_dependency(%q<knjrbfw>, [">= 0"])
    s.add_dependency(%q<datet>, [">= 0"])
    s.add_dependency(%q<hayabusa>, [">= 0"])
    s.add_dependency(%q<http2>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.3"])
  end
end

